### ISSUE TITLE
Description is not Optional! 

### ISSUE THREAD

**Issue by mojienjoyment** [NimaKhajehpour/TaskManager#3]
Description is not optional, I think it should be optional. So I want to have just Title!

**Comment by NimaKhajehpour** [comment]
thanks for the issue and thanks for the heads up on the changing date to time. yes you are right and description can be optional. will consider that in the next update.

**Comment by NimaKhajehpour** [comment]
@mojienjoyment The update is out on repo now and will be up on f-droid soon. the description is optional now and some other minor changes are added as well.
I hope you enjoy the app and thanks for using the app :heart:
